# fly.toml app configuration file generated for portfoliomax on 2025-11-12T16:19:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfoliomax'
primary_region = 'fra'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '22'
    PHP_VERSION = '8.4'

[env]
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_SECURE_COOKIE = 'true'

[processes]
  app = "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf"

[http_service]
  internal_port = 8080
  auto_start_machines = true
  auto_stop_machines = 'stop'
  min_machines_running = 0
  force_https = true
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/"

[mounts]
  source = "portfolio_db"
  destination = "/var/www/html/storage"
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
