# fly.toml app configuration file generated for portfoliomax on 2025-11-12T16:19:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfoliomax'
primary_region = 'fra'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '22'
    PHP_VERSION = '8.4'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[processes]
  app = "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf"

[http_service]
  internal_port = 8080
  force_https = true
  connect_timeout_ms = 8000
  grace_period = "120s"
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "portfolio_db"
  destination = "/var/www/html/storage"
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2


